# Generated by Django 4.2.3 on 2023-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_otpcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
